// Generated by CoffeeScript 1.11.1
(function() {
  var Cli, __parser__, cli, docopt;

  docopt = require('docopt-js');

  __parser__ = function(f) {
    return f.toString().replace(/^[^\/]+\/\*!?/, '').replace(/\*\/[^\/]+$/, '');
  };

  cli = __parser__(function() {

    /*!
    Usage:
      index register <file>
      index status <file>
      index -h | --help
      index --version
     */
  });

  Cli = (function() {
    function Cli() {
      this.initConfig = docopt.docopt(cli, {
        version: '0.0.1'
      });
    }

    return Cli;

  })();

  module.exports = Cli;

}).call(this);
