// Generated by CoffeeScript 1.11.1
(function() {
  var Cli, Guide, Management, defer, enabled;

  defer = require('promise-defer');

  Cli = require('./__cli__');

  Guide = require('./__guide__');

  enabled = true;

  Management = (function() {
    function Management() {
      var cli, d, guide;
      d = defer();
      if (!enabled) {
        return d.reject(enabled) && console.log('Management: Disabled');
      }
      d.resolve(enabled);
      cli = new Cli;
      guide = new Guide(cli);
      d.promise;
    }

    return Management;

  })();

  module.exports = Management;

}).call(this);
