// Generated by CoffeeScript 1.11.1

/*
@fileOverview ./src/management/index.coffee
@description
This module has an index, as it should.
 */

(function() {
  var Cli, Guide, Management, defer, enabled;

  defer = require('promise-defer');

  Cli = require('./__cli__');

  Guide = require('./__guide__');

  enabled = true;


  /*
  @jsdoc
  Implements Management Interfaces.
  @class
  @description
  Management is accompanied by a CLI with a Guide (Interface).
   */

  Management = (function() {
    function Management() {
      var cli, d, guide;
      d = defer();
      if (!enabled) {
        return d.reject(enabled) && console.log('Management: Disabled');
      }
      d.resolve(enabled);
      cli = new Cli;
      guide = new Guide(cli);
      d.promise;
    }

    return Management;

  })();

  module.exports = Management;

}).call(this);
