// Generated by CoffeeScript 1.11.1

/*
@fileOverview ./src/management/qm.coffee
@description
Eventually to grace us as a management system for files that have been 
digested. For now it merely opens a file and passes it along
to the Guide.
 */

(function() {
  var $env, QueryManager, __fs__, __path__, __q__, open_file;

  __q__ = require('promise-defer');

  __path__ = require('path');

  __fs__ = require('fs');

  $env = process.env;

  open_file = function(file) {
    var app_vantage, r, sep;
    sep = '/';
    r = __q__();
    app_vantage = __path__.resolve($env.PWD);
    __fs__.readFile(app_vantage + sep + file, 'utf-8', function(error, data) {
      if (error) {
        return console.log(error);
      }
      return r.resolve(data);
    });
    return r.promise;
  };

  QueryManager = (function() {
    function QueryManager() {
      this.files = null;
    }

    QueryManager.prototype.ls_files = function() {};

    QueryManager.prototype.add_file = function(file) {
      return open_file(file);
    };

    return QueryManager;

  })();

  module.exports = QueryManager;

}).call(this);
