language: node_js
node_js:
  - '5'
  - '5.1'
  - '4'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
before_install: npm install babel-cli babel-preset-es2015 babel-plugin-transform-es2015-spread
install: npm install
before_script: npm run build
