// Generated by CoffeeScript 1.11.1

/*
@fileOverview /index.coffee
@description
Module Index.
 */

(function() {
  var Management, P;

  P = require('bluebird');

  Management = require('./src/management');

  P.resolve(Management());

}).call(this);
