// Generated by CoffeeScript 1.11.1
(function() {
  var Management, P;

  P = require('bluebird');

  Management = require('./src/management');

  P.resolve(Management()).then('./src/api');

}).call(this);
